module.exports = [
  { server: 'arswsint.igslb.allstate.com', path : '/RSPAssistWS/RSPAssistBrokerService/wsdl/RSPAssistBrokerService.wsdl'},
  { server: 'amcalliance.allstate.com', path : '/AgentSale/AMCSaleServiceSoapBindingSoapPort?wsdl'},
  // { server: 'arsintws.allstate.com', path : '/ARSPCI_CC/ARSCC?wsdl'},
  { server: 'arsintws.allstate.com', path : '/EPAS/EPASService/EPASService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/JJ2-0WS/JJInProxyService/WEB-INF/wsdl/JJInProxyService.wsdl'},
  { server: 'www.allstatemotorclub.com', path : '/amctmws/AMCTeleMarketServiceSoapPort?wsdl'},
  { server: 'arsintws.allstate.com', path : '/TokenLookupWS/LookupTokenService/WEB-INF/wsdl/LookupTokenService.wsdl'},
  // { server: 'ghrsws.igslb.allstate.com', path : '/freeTowGHRRegWS/InProxyService?wsdl'},
  // { server: 'ghrsws.igslb.allstate.com', path : '/GHRS2FBWIDGETWS/InProxyService?wsdl'},
  // { server: 'ghrsws.igslb.allstate.com', path : '/GHRS2FBWS/InProxyService?wsdl'},
  // { server: 'ghrsws.igslb.allstate.com', path : '/GHRS-ICSWS/GoodHandsICServiceBrokerService?wsdl'},
  // { s erver: 'ghrsws.igslb.allstate.com', path : '/GHRSREGSTEP1WS/RegStep1InProxyService?wsdl'},
  { server: 'arsextws.allstate.com', path : '/ExternalGateway/GatewayExternalService/GatewayExternalService.wsdl'},
  { server: 'arsextws.allstate.com', path : '/PorscheWS/PorscheBrokerService/WEB-INF/wsdl/PorscheBrokerService.wsdl'},
  { server: 'arsextws.allstate.com', path : '/VailInWS/InBrokerAMCVailService/WEB-INF/wsdl/InBrokerAMCVailService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/AllstateTowSchedulerWS/InBrokerService/WEB-INF/wsdl/InBrokerService.wsdl'},
  // { server: 'arsextws.allstate.com', path : '/AllstateERSWS/ars/ers/maintainPolicyInfo?wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/ArsAmexWS/ArsAmexWSService/WEB-INF/wsdl/ArsAmexWSService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/BMWDiagnostics/services/InProxy/wsdl/InProxy.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/ExperianWS/MMABrokerService/WEB-INF/wsdl/MMABrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/GMACIWS/GMACIBrokerService/WEB-INF/wsdl/GMACIBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/GMGWM/GMGWMInProxyService/GMGWMInProxyService.wsdl'},
  { server: 'arsextws.allstate.com', path : '/HumInbound/HumInboundService/HumInboundService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/InfinityWS/InfinityInProxyService/WEB-INF/wsdl/InfinityInProxyService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/JJ2-0WS/JJInProxyService/WEB-INF/wsdl/JJInProxyService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/JaguarWirelessWS/JaguarWirelessInBrokerService/WEB-INF/wsdl/JaguarWirelessInBrokerService.wsdl'},
  { server: 'arsintws.allstate.com', path : '/JLRWS/DispatchBrokerService/WEB-INF/wsdl/DispatchBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/MemberzPlusWS/MemberzPlusInProxyService/WEB-INF/wsdl/MemberzPlusInProxyService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/MercedesOutWS/InBrokerMBService/WEB-INF/wsdl/InBrokerMBService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/NetworkCar/services/ProxyMMA/wsdl/ProxyMMA.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/NWFWS/NWFInBrokerService/WEB-INF/wsdl/NWFInBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/BMWWirelessWS/BMWWirelessInBrokerService/WEB-INF/wsdl/BMWWirelessInBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/ARSClaimORGWS/NextGenOrgService/WEB-INF/wsdl/NextGenOrgService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/ARSClaimParticipantWS/NextGenClaimService/WEB-INF/wsdl/NextGenClaimService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/PepBoys/services/InProxy/wsdl/InProxy.wsdl'},
  // { server: 'arsextws.allstate.com', path : '/PullXMLGWM/StartJMSListener?wsdl'},
  { server: 'arsextws.allstate.com', path : '/PushEbxmlService/services/InProxy/wsdl/InProxy.wsdl'},
  { server: 'arsextws.allstate.com', path : '/RTDWS/RTDBrokerService/WEB-INF/wsdl/RTDBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/TCHEKWS/InBrokerService/WEB-INF/wsdl/InBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/TChekVMCWS/InBorkerService/WEB-INF/wsdl/InBorkerService.wsdl'},
  { server: 'arsextws.allstate.com', path : '/MobileVASWS/MobileVASBrokerService/WEB-INF/wsdl/MobileVASBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/VinDecoderWS/VinDecoderInBrokerService/WEB-INF/wsdl/VinDecoderInBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/VolkswagenWS/VolkswagenWSInBrokerService/WEB-INF/wsdl/VolkswagenWSInBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/VPWS/VPaymentMCBrokerService/WEB-INF/wsdl/VPaymentMCBrokerService.wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/VTSWS/VTSInBrokerService/WEB-INF/wsdl/VTSInBrokerService.wsdl'},
  { server: 'arswsint.igslb.allstate.com', path : '/MobileAudiConsumerWS/MobileBrokerService/WEB-INF/wsdl/MobileBrokerService.wsdl'},
  { server: 'arswsint.igslb.allstate.com', path : '/MobileEncompassConsumerWS/MobileEncompassBrokerService/WEB-INF/wsdl/MobileEncompassBrokerService.wsdl'},
  { server: 'arswsext.allstate.com', path : '/MobileGenericConsumerWS/GenericBrokerService/GenericBrokerService.wsdl'},
  { server: 'arswsint.igslb.allstate.com', path : '/ARSPushWS/InBrokerService/WEB-INF/wsdl/InBrokerService.wsdl'},
  { server: 'arswsint.igslb.allstate.com', path : '/MobileBMWRSPConsumerWS/BMWBrokerService/WEB-INF/wsdl/BMWBrokerService.wsdl'},
  { server: 'arswsext.allstate.com', path : '/DigitalMessageServiceWS/DMSService/DMSService.wsdl'},
  // { server: 'ghrsws.igslb.allstate.com', path : '/IDMGHRSWS/IdentityManagerService?wsdl'},
  { server: 'arsintws.igslb.allstate.com', path : '/IDMWS/IdentityManagerService/WEB-INF/wsdl/IdentityManagerService.wsdl'},
  { server: 'arswsint.igslb.allstate.com', path : '/ImageHandlerWS/ImageHandlerBrokerService/WEB-INF/wsdl/ImageHandlerBrokerService.wsdl'},
  { server: 'arswsint.igslb.allstate.com', path : '/RSPAssistWS/RSPAssistBrokerService/wsdl/RSPAssistBrokerService.wsdl'}
]
